### PR TITLE
test branch commit

### PR DESCRIPTION
**Pull request by cvelac4**
This is what I have started with for the MapView portions of the game. 

//
//  MapView.swift
//  LibraryEscape
//
//  Created by Carlos Velasco on 4/10/18.
//  Copyright © 2018 Scott Bot Industries. All rights reserved.
//

import Foundation

import MapKit

class ViewController: UIViewController {
    
    @IBOutlet weak var mapView: MKMapView!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        mapView.showsBuildings = true
        let eiffelTowerCoordinates = CLLocationCoordinate2DMake(48.85815,2.29452)
        mapView.region = MKCoordinateRegionMakeWithDistance(eiffelTowerCoordinates, 1000,100)
        
        mapView.mapType = MKMapType.standard
        
        // 3D Camera
        let mapCamera = MKMapCamera()
        mapCamera.centerCoordinate = eiffelTowerCoordinates
        mapCamera.pitch = 45
        mapCamera.altitude = 500
        mapCamera.heading = 45
        
        // Set MKmapView camera property
        self.mapView.camera = mapCamera
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

### CODE REVIEW

**Review by cvelac4 — COMMENTED** [review]
This is what I have started with for the MapView portions of the game.

//
// MapView.swift
// LibraryEscape
//
// Created by Carlos Velasco on 4/10/18.
// Copyright © 2018 Scott Bot Industries. All rights reserved.
//

import Foundation

import MapKit

class ViewController: UIViewController {

@IBOutlet weak var mapView: MKMapView!
override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view, typically from a nib.
    mapView.showsBuildings = true
    let eiffelTowerCoordinates = CLLocationCoordinate2DMake(48.85815,2.29452)
    mapView.region = MKCoordinateRegionMakeWithDistance(eiffelTowerCoordinates, 1000,100)
    
    mapView.mapType = MKMapType.standard
    
    // 3D Camera
    let mapCamera = MKMapCamera()
    mapCamera.centerCoordinate = eiffelTowerCoordinates
    mapCamera.pitch = 45
    mapCamera.altitude = 500
    mapCamera.heading = 45
    
    // Set MKmapView camera property
    self.mapView.camera = mapCamera
}

override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
}
}

**Comment by cvelac4** [comment]
Can you take a look at my new code.

import UIKit

class ViewController: UIViewController{
    @IBOutlet weak var Label: UILabel?
    
    override func viewDidLoad(){
        
        self.Label?.text = "Map View"
        
        
    }
    
    override func didReceiveMemoryWarning(){
    super.didReceiveMemoryWarning()
    }
    
}

**Comment by cvelac4** [comment]
This is the new code I have done for the map view. 

import UIKit

class ViewController: UIViewController{
    @IBOutlet weak var Label: UILabel?
    @IBOutlet weak var Labe2: UILabel?
    @IBOutlet weak var Labe3: UILabel?
    @IBOutlet weak var Labe4: UILabel?
    @IBOutlet weak var Labe5: UILabel?
    
    
    override func viewDidLoad(){
        
        self.Label?.text = "Final Map View"
        self.Labe2?.text = "First Map View"
        self.Labe3?.text = "Second Map View"
        self.Labe4?.text = "Third Map View"
        self.Labe5?.text = "Forth Map View"

        
        
    }
    
    override func didReceiveMemoryWarning(){
    super.didReceiveMemoryWarning()
    }
    
}

**Comment by cvelac4** [comment]
This is my updated code for the Map View if anyone wants to take a look, I am still working on it. 


import UIKit


class MapView : UIScrollView {
    init(name : String) {
        super.init(frame: CGRect(x: 0, y: 0, width: 0, height: 0))
        let height = UIScreen.main.bounds.height / 2
        let width = UIScreen.main.bounds.width
        
        
        let roomName : UILabel = UILabel(frame: CGRect(x: 0, y: 0, width: 0, height: 0))
        
        roomName.text = name
        
        let myImages = ["MapView Final image 1", "MapView Final image 2", "MapView Final image 3", "MapView Final image 4", "MapView Final image" ]
        let imageWidth:CGFloat = 66
        let imageHeight:CGFloat = 66
        var xPosition:CGFloat = 0
        var scrollViewSize:CGFloat=0
        
        for image in myImages {
            let myImage:UIImage = UIImage(named: image)!
            let myImageView:UIImageView = UIImageView()
            myImageView.image = myImage
            
            let LongTapGestureRecognizer = UILongPressGestureRecognizer(target: self, action: "Map View:")
            LongTapGestureRecognizer.minimumPressDuration = 1.0;
            myImageView.addGestureRecognizer(LongTapGestureRecognizer)
            myImageView.isUserInteractionEnabled = true
            
            myImageView.frame.size.width = imageWidth
            myImageView.frame.size.height = imageHeight
            myImageView.frame.origin.x = xPosition
            myImageView.frame.origin.y = 0
            
            //ScrollViewFreunde.addSubview(myImageView)
            //ScrollViewFreunde.showsHorizontalScrollIndicator = false
            xPosition += imageWidth
            scrollViewSize += imageWidth
        }
        //ScrollViewFreunde.contentSize = CGSize(width: imageWidth, height: imageHeight)
        
        
}
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
        func moveTo(room : Room) {
            
          
        }
    
    override func scrollRectToVisible(_ rect: CGRect, animated: Bool) {
        super.scrollRectToVisible(CGRect(x: roomName.xCoord, y: roomName.yCoord, width: width, height: height), animated: true)
    }
    
    }

**Comment by scottbot3000** [comment]
Looks good. Let's have something to show for next week's class.

**Pull request merged**
